name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        env:
          SSH_EC2_PRIVATE_KEY: ${{ secrets.SSH_EC2_PRIVATE_KEY }}
          EC2_REMOTE_USER: ${{ vars.EC2_REMOTE_USER }}
          EC2_REMOTE_SERVER: ${{ vars.EC2_REMOTE_SERVER }}
          EC2_REMOTE_DIR: ${{ vars.EC2_REMOTE_DIR }}
          SSH_OPTIONS: "-o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i /tmp/id_rsa"
        run: |
          
          echo "${SSH_EC2_PRIVATE_KEY}" | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          
          mkdir -p ~/.ssh
          ssh-keyscan "$EC2_REMOTE_SERVER" >> ~/.ssh/known_hosts
          
          SERVICE_NAME=$(basename `git rev-parse --show-toplevel`)
          DIR_TO_UPLOAD="./"
          REMOTE_DIR=$EC2_REMOTE_DIR$SERVICE_NAME/docker
          
          #go get
          ssh $SSH_OPTIONS "$EC2_REMOTE_USER@$EC2_REMOTE_SERVER" 'mkdir -p '$REMOTE_DIR
          rsync -avz --delete-before -e "ssh $SSH_OPTIONS" --exclude '.git' $DIR_TO_UPLOAD "$EC2_REMOTE_USER@$EC2_REMOTE_SERVER:$REMOTE_DIR"
          ssh $SSH_OPTIONS "$EC2_REMOTE_USER@$EC2_REMOTE_SERVER" 'cd '$REMOTE_DIR' && docker-compose up -d --build --force-recreate --remove-orphans'
          rm /tmp/id_rsa
